### ISSUE TITLE
Dual radiator and D5 pump support?

### ISSUE THREAD

**Issue by fabioneves** [CircleTect/space-case#2]
Hello,

Any chance of having a version of a dual radiator 280 setup? (top/bottom)
Also having space to fit a D5 would be awesome.

Great job,
Thanks!

**Comment by CircleTect** [comment]
There's plenty of room for a D5 already - just need to make a bracket for it. 

The radiator (240 or 280) is designed to fit on the frame in the location indicated in the [video here](https://youtu.be/Zg2zSBpEYaU?t=307).

**Comment by fabioneves** [comment]
Thank you for the answer. Unfortunately a single radiator for todays hardware is not enough.

Merry Xmas, keep up the good work 😊
